name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'rc/**'

jobs:
  deploy:
    uses: crashteamdev/jvm-workflows/.github/workflows/maven-library-deploy.yml@v1
    with:
      java-version: 21
    secrets:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_TOKEN }}
      deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
